### ISSUE TITLE
My Schedule missing classes

### ISSUE THREAD

**Issue by demetrios-koziris** [jguerinet/MyMartlet#87]
Classes on Monday and Wednesday are missing from the calendar in the My Schedule tab. 

For me, the missing classes are MATH-240 Lec 001 (CRN 435), MATH-240 Tut 002 (CRN 21382), and MATH-323 Tut 002 (CRN 22841). 

Tuesday, Thursday, and Friday appear as expected which includes MATH323 Lec 001 (CRN 445) even though the tutorial is missing (this would seem to indicate the issue is related to the day of the week rather than to specific courses).

All the lectures and tutorials appear as expected in the My Classes tab.

**Comment by jguerinet** [comment]
Hey @demetrios-koziris, 
Yeah this problem has been reported a couple of times. I dug into it and it's because I wrongly assumed that a specific time could only have 1 CRN, which I was using as a unique Id. Turns out 1 CRN could be associated to multiple course times. 
Currently fixing it, hoping to have a version out by tomorrow evening.

**Comment by jguerinet** [comment]
Hey @demetrios-koziris, should be fixed in v1.0.1 released last week!
